"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Shape_1 = require("./Shape");
const Circle_1 = require("./Circle");
const Rectangle_1 = require("./Rectangle");
let myShape = new Shape_1.Shape(20, 30);
console.log(myShape.getInfo());
let myCircle = new Circle_1.Circle(10, 20, 4);
console.log(myCircle.getInfo());
let myRectangle = new Rectangle_1.Rectangle(2, 3, 45, 65);
console.log(myRectangle.getInfo());
